/**
 * Capital cities, for the capitals prompt in "Name that country".
 *
 * Hand-written, like the continent table, because a surprising number of these
 * are contested or plural and the choice deserves to be visible. The generator
 * checks every country has exactly one, so a gap fails the build.
 *
 * These are **not translated**. Country names come from CLDR, but there is no
 * equivalent source for city names in the browser, and hand-writing 196 cities
 * in ten languages is not worth it. A capital is a proper noun that mostly
 * transliterates, so the prompt stays Latin even when the game is in Hebrew —
 * the answer is a country name, which is translated.
 */

import type { CountryCode } from './types.ts'

export const CAPITALS: Readonly<Record<CountryCode, string>> = {
  AFG: 'Kabul',
  AGO: 'Luanda',
  ALB: 'Tirana',
  AND: 'Andorra la Vella',
  ARE: 'Abu Dhabi',
  ARG: 'Buenos Aires',
  ARM: 'Yerevan',
  ATG: "Saint John's",
  AUS: 'Canberra',
  AUT: 'Vienna',
  AZE: 'Baku',
  BDI: 'Gitega', // moved from Bujumbura in 2019
  BEL: 'Brussels',
  BEN: 'Porto-Novo', // official; Cotonou is the seat of government
  BFA: 'Ouagadougou',
  BGD: 'Dhaka',
  BGR: 'Sofia',
  BHR: 'Manama',
  BHS: 'Nassau',
  BIH: 'Sarajevo',
  BLR: 'Minsk',
  BLZ: 'Belmopan',
  BOL: 'Sucre', // constitutional; La Paz is the seat of government
  BRA: 'Brasília',
  BRB: 'Bridgetown',
  BRN: 'Bandar Seri Begawan',
  BTN: 'Thimphu',
  BWA: 'Gaborone',
  CAF: 'Bangui',
  CAN: 'Ottawa',
  CHE: 'Bern',
  CHL: 'Santiago',
  CHN: 'Beijing',
  CIV: 'Yamoussoukro', // official; Abidjan is the largest city and de facto seat
  CMR: 'Yaoundé',
  COD: 'Kinshasa',
  COG: 'Brazzaville',
  COL: 'Bogotá',
  COM: 'Moroni',
  CPV: 'Praia',
  CRI: 'San José',
  CUB: 'Havana',
  CYP: 'Nicosia',
  CZE: 'Prague',
  DEU: 'Berlin',
  DJI: 'Djibouti',
  DMA: 'Roseau',
  DNK: 'Copenhagen',
  DOM: 'Santo Domingo',
  DZA: 'Algiers',
  ECU: 'Quito',
  EGY: 'Cairo',
  ERI: 'Asmara',
  ESP: 'Madrid',
  EST: 'Tallinn',
  ETH: 'Addis Ababa',
  FIN: 'Helsinki',
  FJI: 'Suva',
  FRA: 'Paris',
  FSM: 'Palikir',
  GAB: 'Libreville',
  GBR: 'London',
  GEO: 'Tbilisi',
  GHA: 'Accra',
  GIN: 'Conakry',
  GMB: 'Banjul',
  GNB: 'Bissau',
  GNQ: 'Malabo',
  GRC: 'Athens',
  GRD: "Saint George's",
  GTM: 'Guatemala City',
  GUY: 'Georgetown',
  HND: 'Tegucigalpa',
  HRV: 'Zagreb',
  HTI: 'Port-au-Prince',
  HUN: 'Budapest',
  IDN: 'Jakarta', // Nusantara is being built to replace it
  IND: 'New Delhi',
  IRL: 'Dublin',
  IRN: 'Tehran',
  IRQ: 'Baghdad',
  ISL: 'Reykjavík',
  ISR: 'Jerusalem', // seat of government; internationally contested
  ITA: 'Rome',
  JAM: 'Kingston',
  JOR: 'Amman',
  JPN: 'Tokyo',
  KAZ: 'Astana',
  KEN: 'Nairobi',
  KGZ: 'Bishkek',
  KHM: 'Phnom Penh',
  KIR: 'Tarawa',
  KNA: 'Basseterre',
  KOR: 'Seoul',
  KWT: 'Kuwait City',
  LAO: 'Vientiane',
  LBN: 'Beirut',
  LBR: 'Monrovia',
  LBY: 'Tripoli',
  LCA: 'Castries',
  LIE: 'Vaduz',
  LKA: 'Colombo', // Sri Jayawardenepura Kotte is the legislative capital
  LSO: 'Maseru',
  LTU: 'Vilnius',
  LUX: 'Luxembourg',
  LVA: 'Riga',
  MAR: 'Rabat',
  MCO: 'Monaco',
  MDA: 'Chișinău',
  MDG: 'Antananarivo',
  MDV: 'Malé',
  MEX: 'Mexico City',
  MHL: 'Majuro',
  MKD: 'Skopje',
  MLI: 'Bamako',
  MLT: 'Valletta',
  MMR: 'Naypyidaw',
  MNE: 'Podgorica',
  MNG: 'Ulaanbaatar',
  MOZ: 'Maputo',
  MRT: 'Nouakchott',
  MUS: 'Port Louis',
  MWI: 'Lilongwe',
  MYS: 'Kuala Lumpur',
  NAM: 'Windhoek',
  NER: 'Niamey',
  NGA: 'Abuja',
  NIC: 'Managua',
  NLD: 'Amsterdam', // constitutional; The Hague is the seat of government
  NOR: 'Oslo',
  NPL: 'Kathmandu',
  NRU: 'Yaren',
  NZL: 'Wellington',
  OMN: 'Muscat',
  PAK: 'Islamabad',
  PAN: 'Panama City',
  PER: 'Lima',
  PHL: 'Manila',
  PLW: 'Ngerulmud',
  PNG: 'Port Moresby',
  POL: 'Warsaw',
  PRK: 'Pyongyang',
  PRT: 'Lisbon',
  PRY: 'Asunción',
  PSE: 'Ramallah', // administrative seat; East Jerusalem is claimed
  QAT: 'Doha',
  ROU: 'Bucharest',
  RUS: 'Moscow',
  RWA: 'Kigali',
  SAU: 'Riyadh',
  SDN: 'Khartoum',
  SEN: 'Dakar',
  SGP: 'Singapore',
  SLB: 'Honiara',
  SLE: 'Freetown',
  SLV: 'San Salvador',
  SMR: 'San Marino',
  SOM: 'Mogadishu',
  SRB: 'Belgrade',
  SSD: 'Juba',
  STP: 'São Tomé',
  SUR: 'Paramaribo',
  SVK: 'Bratislava',
  SVN: 'Ljubljana',
  SWE: 'Stockholm',
  SWZ: 'Mbabane', // executive; Lobamba is the legislative and royal capital
  SYC: 'Victoria',
  SYR: 'Damascus',
  TCD: "N'Djamena",
  TGO: 'Lomé',
  THA: 'Bangkok',
  TJK: 'Dushanbe',
  TKM: 'Ashgabat',
  TLS: 'Dili',
  TON: "Nuku'alofa",
  TTO: 'Port of Spain',
  TUN: 'Tunis',
  TUR: 'Ankara',
  TWN: 'Taipei',
  TZA: 'Dodoma', // Dar es Salaam remains the largest city
  UGA: 'Kampala',
  UKR: 'Kyiv',
  URY: 'Montevideo',
  USA: 'Washington, D.C.',
  UZB: 'Tashkent',
  VAT: 'Vatican City',
  VCT: 'Kingstown',
  VEN: 'Caracas',
  VNM: 'Hanoi',
  VUT: 'Port Vila',
  WSM: 'Apia',
  XKX: 'Pristina',
  YEM: 'Sanaa', // Aden is the temporary seat of the recognised government
  ZAF: 'Pretoria', // executive; Cape Town legislates and Bloemfontein judges
  ZMB: 'Lusaka',
  ZWE: 'Harare',
}

export function capitalOf(code: CountryCode): string | undefined {
  return CAPITALS[code]
}
