/**
 * Languages the game is playable in.
 *
 * Country names come from `i18n-iso-countries` at build time, so adding a
 * language is: add a row here, write its `Strings`, run `npm run graph`. The
 * package ships 76 locales, so the limit is the interface text below, not the
 * country data.
 *
 * Guess matching is deliberately not limited to the chosen language — see
 * `findByName` in graph.ts. Two people playing together can each read the game
 * in their own language and still type into the same board.
 */

import type { ContinentId } from './continents.ts'

export type LanguageCode = 'en' | 'he' | 'ar' | 'es' | 'fr' | 'de' | 'it' | 'nl' | 'pt' | 'ru'

export type Language = {
  readonly code: LanguageCode
  /** What speakers call it, which is what belongs in the picker. */
  readonly endonym: string
  readonly dir: 'ltr' | 'rtl'
}

export const LANGUAGES: readonly Language[] = [
  { code: 'en', endonym: 'English', dir: 'ltr' },
  { code: 'he', endonym: 'עברית', dir: 'rtl' },
  { code: 'ar', endonym: 'العربية', dir: 'rtl' },
  { code: 'es', endonym: 'Español', dir: 'ltr' },
  { code: 'fr', endonym: 'Français', dir: 'ltr' },
  { code: 'de', endonym: 'Deutsch', dir: 'ltr' },
  { code: 'it', endonym: 'Italiano', dir: 'ltr' },
  { code: 'nl', endonym: 'Nederlands', dir: 'ltr' },
  { code: 'pt', endonym: 'Português', dir: 'ltr' },
  { code: 'ru', endonym: 'Русский', dir: 'ltr' },
]

export const DEFAULT_LANGUAGE: LanguageCode = 'en'

export const LANGUAGE_CODES: readonly LanguageCode[] = LANGUAGES.map((language) => language.code)

export function isLanguageCode(value: string): value is LanguageCode {
  return LANGUAGE_CODES.includes(value as LanguageCode)
}

export function languageOf(code: LanguageCode): Language {
  return LANGUAGES.find((language) => language.code === code) ?? LANGUAGES[0]!
}

/**
 * Interface text. Counts are shown as `label: n` rather than folded into a
 * sentence, because "3 more countries" needs different agreement in most of
 * these languages and a label sidesteps every one of those rules.
 */
export type Strings = {
  title: string
  tagline: string
  language: string

  twoPhones: string
  twoPhonesHint: string
  startGame: string
  codePlaceholder: string
  join: string
  codeError: string
  oneDevice: string
  oneDeviceHint: string
  playHere: string

  score: string
  par: string
  yourStart: string
  stillNeeded: string
  guessPlaceholder: string
  guessingAs: string
  player: string

  waiting: string
  bothHere: string
  reconnecting: string
  connecting: string
  invite: string
  copied: string
  leave: string
  back: string
  wholeWorld: string

  youMet: string
  perfect: string
  againstPar: string
  yourRoute: string
  shortestRoute: string
  newGame: string

  you: string
  partner: string
  partnerNamed: string

  rejectUnknown: string
  rejectOutOfPlay: string
  rejectWrongLandmass: string
  rejectAlreadyNamed: string
  rejectGameOver: string

  errBadRoom: string
  errRoomFull: string
  errTakenOver: string
  errGeneric: string

  modeMeet: string
  modeMeetHint: string
  modeContinent: string
  modeContinentHint: string
  chooseContinent: string
  randomContinent: string
  named: string
  missed: string
  giveUp: string
  filledIt: string
  gaveUp: string
  rejectWrongContinent: string
  showOutlines: string
  hideOutlines: string
  modeIdentify: string
  modeIdentifyHint: string
  whichCountry: string
  skip: string
  correct: string
  continents: Readonly<Record<ContinentId, string>>
}

export const STRINGS: Readonly<Record<LanguageCode, Strings>> = {
  en: {
    title: 'Meet in the Middle',
    tagline:
      'You each start in a secret country. Name countries — any country, in any order — until your two sides join up. Fewer is better.',
    language: 'Language',
    twoPhones: 'Two phones',
    twoPhonesHint: 'One of you starts a game and sends the other the link.',
    startGame: 'Start a game',
    codePlaceholder: 'Or enter a code',
    join: 'Join',
    codeError: 'Room codes are four characters.',
    oneDevice: 'One device',
    oneDeviceHint: 'Pass it back and forth, or play both sides yourself.',
    playHere: 'Play here',
    score: 'Score',
    par: 'Par',
    yourStart: 'Your start',
    stillNeeded: 'Still needed',
    guessPlaceholder: 'Name any country',
    guessingAs: 'Guessing as',
    player: 'Player',
    waiting: 'Waiting for your partner',
    bothHere: 'Both here',
    reconnecting: 'Reconnecting…',
    connecting: 'Connecting…',
    invite: 'Invite',
    copied: 'Copied',
    leave: 'Leave',
    back: 'Back',
    wholeWorld: 'Whole world',
    youMet: 'You met',
    perfect: 'Perfect — nobody could have done it in fewer.',
    againstPar: 'Score {score}, par {par}.',
    yourRoute: 'Your route',
    shortestRoute: 'Shortest possible',
    newGame: 'New game',
    you: 'You',
    partner: 'Partner',
    partnerNamed: 'Partner has named',
    rejectUnknown: '"{text}" is not a country in this game.',
    rejectOutOfPlay: '{country} has no land border with anywhere.',
    rejectWrongLandmass: '{country} is on another landmass.',
    rejectAlreadyNamed: '{country} is already on the board.',
    rejectGameOver: 'You already met.',
    errBadRoom: 'That room code does not look right.',
    errRoomFull: 'That room already has two players.',
    errTakenOver: 'You opened this game somewhere else.',
    errGeneric: 'Something went wrong.',
    modeMeet: 'Meet in the middle',
    modeMeetHint: 'Two secret starts. Name countries until your two sides join up.',
    modeContinent: 'Fill a continent',
    modeContinentHint: 'No starts. Name every country in one continent, together.',
    chooseContinent: 'Which continent?',
    randomContinent: 'Surprise us',
    named: 'Named',
    missed: 'Missed',
    giveUp: 'Show what is left',
    filledIt: 'You filled it in',
    gaveUp: 'Here is the rest',
    rejectWrongContinent: '{country} is not in this continent.',
    showOutlines: 'Show outlines',
    hideOutlines: 'Hide outlines',
    modeIdentify: 'Name that country',
    modeIdentifyHint: 'One country lights up on the map. Say which it is.',
    whichCountry: 'Which country is highlighted?',
    skip: 'Skip',
    correct: 'Right',
    continents: {
      europe: 'Europe',
      asia: 'Asia',
      africa: 'Africa',
      'north-america': 'North America',
      'south-america': 'South America',
      oceania: 'Oceania',
    },
  },

  he: {
    title: 'להיפגש באמצע',
    tagline:
      'כל אחד מכם מתחיל במדינה סודית. תנו שמות של מדינות — כל מדינה, בכל סדר — עד ששני הצדדים מתחברים. כמה שפחות, יותר טוב.',
    language: 'שפה',
    twoPhones: 'שני טלפונים',
    twoPhonesHint: 'אחד מכם פותח משחק ושולח לשני את הקישור.',
    startGame: 'פתיחת משחק',
    codePlaceholder: 'או הזינו קוד',
    join: 'הצטרפות',
    codeError: 'קוד חדר הוא ארבעה תווים.',
    oneDevice: 'מכשיר אחד',
    oneDeviceHint: 'העבירו אותו ביניכם, או שחקו את שני הצדדים.',
    playHere: 'לשחק כאן',
    score: 'ניקוד',
    par: 'מינימום',
    yourStart: 'נקודת הפתיחה שלך',
    stillNeeded: 'נותרו',
    guessPlaceholder: 'שם של מדינה',
    guessingAs: 'משחקים בתור',
    player: 'שחקן',
    waiting: 'ממתינים לשותף',
    bothHere: 'שניכם כאן',
    reconnecting: 'מתחבר מחדש…',
    connecting: 'מתחבר…',
    invite: 'הזמנה',
    copied: 'הועתק',
    leave: 'יציאה',
    back: 'חזרה',
    wholeWorld: 'כל העולם',
    youMet: 'נפגשתם',
    perfect: 'מושלם — אי אפשר היה בפחות.',
    againstPar: 'ניקוד {score}, מינימום {par}.',
    yourRoute: 'המסלול שלכם',
    shortestRoute: 'המסלול הקצר ביותר',
    newGame: 'משחק חדש',
    you: 'שלי',
    partner: 'השותף',
    partnerNamed: 'השותף ציין',
    rejectUnknown: '״{text}״ אינה מדינה במשחק הזה.',
    rejectOutOfPlay: 'ל{country} אין גבול יבשתי עם אף מדינה.',
    rejectWrongLandmass: '{country} נמצאת ביבשת אחרת.',
    rejectAlreadyNamed: '{country} כבר על הלוח.',
    rejectGameOver: 'כבר נפגשתם.',
    errBadRoom: 'קוד החדר לא נראה תקין.',
    errRoomFull: 'בחדר הזה כבר יש שני שחקנים.',
    errTakenOver: 'פתחתם את המשחק במקום אחר.',
    errGeneric: 'משהו השתבש.',
    modeMeet: 'להיפגש באמצע',
    modeMeetHint: 'שתי נקודות פתיחה סודיות. תנו שמות של מדינות עד ששני הצדדים מתחברים.',
    modeContinent: 'למלא יבשת',
    modeContinentHint: 'בלי נקודת פתיחה. תנו יחד שמות של כל המדינות ביבשת אחת.',
    chooseContinent: 'איזו יבשת?',
    randomContinent: 'תפתיעו אותנו',
    named: 'נאמרו',
    missed: 'חסרו',
    giveUp: 'להראות מה נשאר',
    filledIt: 'מילאתם את הכל',
    gaveUp: 'הנה השאר',
    rejectWrongContinent: '{country} לא נמצאת ביבשת הזאת.',
    showOutlines: 'להראות גבולות',
    hideOutlines: 'להסתיר גבולות',
    modeIdentify: 'נחשו את המדינה',
    modeIdentifyHint: 'מדינה אחת נדלקת על המפה. אמרו איזו.',
    whichCountry: 'איזו מדינה מסומנת?',
    skip: 'לדלג',
    correct: 'נכון',
    continents: {
      europe: 'אירופה',
      asia: 'אסיה',
      africa: 'אפריקה',
      'north-america': 'צפון אמריקה',
      'south-america': 'דרום אמריקה',
      oceania: 'אוקיאניה',
    },
  },

  ar: {
    title: 'نلتقي في المنتصف',
    tagline:
      'يبدأ كل منكما في دولة سرية. اذكرا أسماء دول — أي دولة، بأي ترتيب — حتى يتصل الجانبان. كلما قل العدد كان أفضل.',
    language: 'اللغة',
    twoPhones: 'هاتفان',
    twoPhonesHint: 'يبدأ أحدكما اللعبة ويرسل الرابط للآخر.',
    startGame: 'بدء لعبة',
    codePlaceholder: 'أو أدخل رمزًا',
    join: 'انضمام',
    codeError: 'رمز الغرفة من أربعة أحرف.',
    oneDevice: 'جهاز واحد',
    oneDeviceHint: 'تناوبا عليه، أو العب الجانبين بنفسك.',
    playHere: 'اللعب هنا',
    score: 'النتيجة',
    par: 'الحد الأدنى',
    yourStart: 'نقطة البداية',
    stillNeeded: 'المتبقي',
    guessPlaceholder: 'اسم أي دولة',
    guessingAs: 'تلعب باسم',
    player: 'لاعب',
    waiting: 'في انتظار شريكك',
    bothHere: 'كلاكما هنا',
    reconnecting: 'إعادة الاتصال…',
    connecting: 'جارٍ الاتصال…',
    invite: 'دعوة',
    copied: 'تم النسخ',
    leave: 'خروج',
    back: 'رجوع',
    wholeWorld: 'العالم كله',
    youMet: 'التقيتما',
    perfect: 'ممتاز — لا يمكن بأقل من ذلك.',
    againstPar: 'النتيجة {score}، الحد الأدنى {par}.',
    yourRoute: 'مساركما',
    shortestRoute: 'أقصر مسار ممكن',
    newGame: 'لعبة جديدة',
    you: 'أنت',
    partner: 'الشريك',
    partnerNamed: 'ذكر الشريك',
    rejectUnknown: '«{text}» ليست دولة في هذه اللعبة.',
    rejectOutOfPlay: '{country} ليس لها حدود برية مع أي دولة.',
    rejectWrongLandmass: '{country} في كتلة يابسة أخرى.',
    rejectAlreadyNamed: '{country} موجودة بالفعل على اللوح.',
    rejectGameOver: 'لقد التقيتما بالفعل.',
    errBadRoom: 'رمز الغرفة غير صحيح.',
    errRoomFull: 'في هذه الغرفة لاعبان بالفعل.',
    errTakenOver: 'لقد فتحت اللعبة في مكان آخر.',
    errGeneric: 'حدث خطأ ما.',
    modeMeet: 'نلتقي في المنتصف',
    modeMeetHint: 'نقطتا بداية سريتان. اذكرا أسماء دول حتى يتصل الجانبان.',
    modeContinent: 'املأ قارة',
    modeContinentHint: 'بلا نقطة بداية. اذكرا معًا كل دول قارة واحدة.',
    chooseContinent: 'أي قارة؟',
    randomContinent: 'فاجئنا',
    named: 'مذكورة',
    missed: 'فائتة',
    giveUp: 'أظهر ما تبقى',
    filledIt: 'أكملتماها',
    gaveUp: 'وهذا الباقي',
    rejectWrongContinent: '{country} ليست في هذه القارة.',
    showOutlines: 'إظهار الحدود',
    hideOutlines: 'إخفاء الحدود',
    modeIdentify: 'خمّن الدولة',
    modeIdentifyHint: 'تضيء دولة واحدة على الخريطة. قل أيها.',
    whichCountry: 'أي دولة مضاءة؟',
    skip: 'تخطٍّ',
    correct: 'صحيح',
    continents: {
      europe: 'أوروبا',
      asia: 'آسيا',
      africa: 'أفريقيا',
      'north-america': 'أمريكا الشمالية',
      'south-america': 'أمريكا الجنوبية',
      oceania: 'أوقيانوسيا',
    },
  },

  es: {
    title: 'Encontrarse en el medio',
    tagline:
      'Cada uno empieza en un país secreto. Nombrad países — cualquiera, en cualquier orden — hasta que los dos lados se unan. Cuantos menos, mejor.',
    language: 'Idioma',
    twoPhones: 'Dos móviles',
    twoPhonesHint: 'Uno empieza la partida y envía el enlace al otro.',
    startGame: 'Empezar partida',
    codePlaceholder: 'O introduce un código',
    join: 'Unirse',
    codeError: 'Los códigos son de cuatro caracteres.',
    oneDevice: 'Un dispositivo',
    oneDeviceHint: 'Pasáoslo, o juega los dos lados tú mismo.',
    playHere: 'Jugar aquí',
    score: 'Puntos',
    par: 'Mínimo',
    yourStart: 'Tu inicio',
    stillNeeded: 'Faltan',
    guessPlaceholder: 'Nombra un país',
    guessingAs: 'Juegas como',
    player: 'Jugador',
    waiting: 'Esperando a tu compañero',
    bothHere: 'Los dos aquí',
    reconnecting: 'Reconectando…',
    connecting: 'Conectando…',
    invite: 'Invitar',
    copied: 'Copiado',
    leave: 'Salir',
    back: 'Volver',
    wholeWorld: 'Todo el mundo',
    youMet: 'Os habéis encontrado',
    perfect: 'Perfecto — nadie lo habría hecho con menos.',
    againstPar: 'Puntos {score}, mínimo {par}.',
    yourRoute: 'Vuestra ruta',
    shortestRoute: 'La ruta más corta',
    newGame: 'Nueva partida',
    you: 'Tú',
    partner: 'Compañero',
    partnerNamed: 'Tu compañero ha nombrado',
    rejectUnknown: '«{text}» no es un país de este juego.',
    rejectOutOfPlay: '{country} no tiene frontera terrestre con nadie.',
    rejectWrongLandmass: '{country} está en otra masa de tierra.',
    rejectAlreadyNamed: '{country} ya está en el tablero.',
    rejectGameOver: 'Ya os habéis encontrado.',
    errBadRoom: 'Ese código de sala no parece correcto.',
    errRoomFull: 'Esa sala ya tiene dos jugadores.',
    errTakenOver: 'Has abierto el juego en otro sitio.',
    errGeneric: 'Algo ha salido mal.',
    modeMeet: 'Encontrarse en el medio',
    modeMeetHint: 'Dos inicios secretos. Nombrad países hasta que los dos lados se unan.',
    modeContinent: 'Llenar un continente',
    modeContinentHint: 'Sin inicios. Nombrad juntos todos los países de un continente.',
    chooseContinent: '¿Qué continente?',
    randomContinent: 'Sorpréndenos',
    named: 'Nombrados',
    missed: 'Faltaron',
    giveUp: 'Mostrar lo que queda',
    filledIt: 'Lo habéis completado',
    gaveUp: 'Esto es lo que faltaba',
    rejectWrongContinent: '{country} no está en este continente.',
    showOutlines: 'Mostrar contornos',
    hideOutlines: 'Ocultar contornos',
    modeIdentify: 'Adivina el país',
    modeIdentifyHint: 'Un país se ilumina en el mapa. Di cuál es.',
    whichCountry: '¿Qué país está marcado?',
    skip: 'Saltar',
    correct: 'Aciertos',
    continents: {
      europe: 'Europa',
      asia: 'Asia',
      africa: 'África',
      'north-america': 'América del Norte',
      'south-america': 'América del Sur',
      oceania: 'Oceanía',
    },
  },

  fr: {
    title: 'Se retrouver au milieu',
    tagline:
      'Chacun commence dans un pays secret. Nommez des pays — n’importe lequel, dans n’importe quel ordre — jusqu’à ce que vos deux côtés se rejoignent. Le moins possible.',
    language: 'Langue',
    twoPhones: 'Deux téléphones',
    twoPhonesHint: 'L’un lance la partie et envoie le lien à l’autre.',
    startGame: 'Lancer une partie',
    codePlaceholder: 'Ou saisissez un code',
    join: 'Rejoindre',
    codeError: 'Les codes font quatre caractères.',
    oneDevice: 'Un seul appareil',
    oneDeviceHint: 'Passez-le-vous, ou jouez les deux côtés.',
    playHere: 'Jouer ici',
    score: 'Score',
    par: 'Minimum',
    yourStart: 'Votre départ',
    stillNeeded: 'Restant',
    guessPlaceholder: 'Nommez un pays',
    guessingAs: 'Vous jouez',
    player: 'Joueur',
    waiting: 'En attente de votre partenaire',
    bothHere: 'Tous les deux là',
    reconnecting: 'Reconnexion…',
    connecting: 'Connexion…',
    invite: 'Inviter',
    copied: 'Copié',
    leave: 'Quitter',
    back: 'Retour',
    wholeWorld: 'Monde entier',
    youMet: 'Vous vous êtes rejoints',
    perfect: 'Parfait — impossible de faire moins.',
    againstPar: 'Score {score}, minimum {par}.',
    yourRoute: 'Votre trajet',
    shortestRoute: 'Le plus court possible',
    newGame: 'Nouvelle partie',
    you: 'Vous',
    partner: 'Partenaire',
    partnerNamed: 'Votre partenaire a nommé',
    rejectUnknown: '« {text} » n’est pas un pays de ce jeu.',
    rejectOutOfPlay: '{country} n’a de frontière terrestre avec personne.',
    rejectWrongLandmass: '{country} est sur une autre masse continentale.',
    rejectAlreadyNamed: '{country} est déjà sur le plateau.',
    rejectGameOver: 'Vous vous êtes déjà rejoints.',
    errBadRoom: 'Ce code de salon ne semble pas correct.',
    errRoomFull: 'Ce salon a déjà deux joueurs.',
    errTakenOver: 'Vous avez ouvert le jeu ailleurs.',
    errGeneric: 'Une erreur est survenue.',
    modeMeet: 'Se retrouver au milieu',
    modeMeetHint: 'Deux départs secrets. Nommez des pays jusqu’à ce que vos deux côtés se rejoignent.',
    modeContinent: 'Remplir un continent',
    modeContinentHint: 'Aucun départ. Nommez ensemble tous les pays d’un continent.',
    chooseContinent: 'Quel continent ?',
    randomContinent: 'Surprenez-nous',
    named: 'Nommés',
    missed: 'Manqués',
    giveUp: 'Montrer ce qui reste',
    filledIt: 'Vous l’avez rempli',
    gaveUp: 'Voici le reste',
    rejectWrongContinent: '{country} n’est pas sur ce continent.',
    showOutlines: 'Afficher les contours',
    hideOutlines: 'Masquer les contours',
    modeIdentify: 'Devinez le pays',
    modeIdentifyHint: 'Un pays s’allume sur la carte. Dites lequel.',
    whichCountry: 'Quel pays est en surbrillance ?',
    skip: 'Passer',
    correct: 'Justes',
    continents: {
      europe: 'Europe',
      asia: 'Asie',
      africa: 'Afrique',
      'north-america': 'Amérique du Nord',
      'south-america': 'Amérique du Sud',
      oceania: 'Océanie',
    },
  },

  de: {
    title: 'In der Mitte treffen',
    tagline:
      'Ihr startet jeweils in einem geheimen Land. Nennt Länder — irgendeins, in beliebiger Reihenfolge — bis eure beiden Seiten sich verbinden. Je weniger, desto besser.',
    language: 'Sprache',
    twoPhones: 'Zwei Handys',
    twoPhonesHint: 'Einer startet ein Spiel und schickt dem anderen den Link.',
    startGame: 'Spiel starten',
    codePlaceholder: 'Oder Code eingeben',
    join: 'Beitreten',
    codeError: 'Raumcodes haben vier Zeichen.',
    oneDevice: 'Ein Gerät',
    oneDeviceHint: 'Reicht es herum, oder spielt beide Seiten selbst.',
    playHere: 'Hier spielen',
    score: 'Punkte',
    par: 'Minimum',
    yourStart: 'Dein Start',
    stillNeeded: 'Noch nötig',
    guessPlaceholder: 'Nenne ein Land',
    guessingAs: 'Du spielst als',
    player: 'Spieler',
    waiting: 'Warte auf deinen Partner',
    bothHere: 'Beide da',
    reconnecting: 'Neu verbinden…',
    connecting: 'Verbinde…',
    invite: 'Einladen',
    copied: 'Kopiert',
    leave: 'Verlassen',
    back: 'Zurück',
    wholeWorld: 'Ganze Welt',
    youMet: 'Ihr habt euch getroffen',
    perfect: 'Perfekt — mit weniger ging es nicht.',
    againstPar: 'Punkte {score}, Minimum {par}.',
    yourRoute: 'Euer Weg',
    shortestRoute: 'Kürzester Weg',
    newGame: 'Neues Spiel',
    you: 'Du',
    partner: 'Partner',
    partnerNamed: 'Partner nannte',
    rejectUnknown: '„{text}“ ist in diesem Spiel kein Land.',
    rejectOutOfPlay: '{country} hat keine Landgrenze zu irgendjemandem.',
    rejectWrongLandmass: '{country} liegt auf einer anderen Landmasse.',
    rejectAlreadyNamed: '{country} steht schon auf dem Brett.',
    rejectGameOver: 'Ihr habt euch schon getroffen.',
    errBadRoom: 'Dieser Raumcode sieht nicht richtig aus.',
    errRoomFull: 'In diesem Raum sind schon zwei Spieler.',
    errTakenOver: 'Du hast das Spiel woanders geöffnet.',
    errGeneric: 'Etwas ist schiefgelaufen.',
    modeMeet: 'In der Mitte treffen',
    modeMeetHint: 'Zwei geheime Startländer. Nennt Länder, bis eure Seiten sich verbinden.',
    modeContinent: 'Einen Kontinent füllen',
    modeContinentHint: 'Kein Start. Nennt gemeinsam jedes Land eines Kontinents.',
    chooseContinent: 'Welcher Kontinent?',
    randomContinent: 'Überrascht uns',
    named: 'Genannt',
    missed: 'Gefehlt',
    giveUp: 'Rest anzeigen',
    filledIt: 'Ihr habt ihn vollgemacht',
    gaveUp: 'Hier ist der Rest',
    rejectWrongContinent: '{country} liegt nicht auf diesem Kontinent.',
    showOutlines: 'Umrisse zeigen',
    hideOutlines: 'Umrisse ausblenden',
    modeIdentify: 'Errate das Land',
    modeIdentifyHint: 'Ein Land leuchtet auf der Karte auf. Sag welches.',
    whichCountry: 'Welches Land ist markiert?',
    skip: 'Überspringen',
    correct: 'Richtig',
    continents: {
      europe: 'Europa',
      asia: 'Asien',
      africa: 'Afrika',
      'north-america': 'Nordamerika',
      'south-america': 'Südamerika',
      oceania: 'Ozeanien',
    },
  },

  it: {
    title: 'Incontrarsi a metà strada',
    tagline:
      'Ognuno parte da un paese segreto. Nominate paesi — uno qualsiasi, in qualsiasi ordine — finché i due lati non si uniscono. Meno sono, meglio è.',
    language: 'Lingua',
    twoPhones: 'Due telefoni',
    twoPhonesHint: 'Uno di voi apre una partita e manda il link all’altro.',
    startGame: 'Inizia una partita',
    codePlaceholder: 'Oppure inserisci un codice',
    join: 'Entra',
    codeError: 'I codici sono di quattro caratteri.',
    oneDevice: 'Un dispositivo',
    oneDeviceHint: 'Passatevelo, o gioca tu entrambi i lati.',
    playHere: 'Gioca qui',
    score: 'Punti',
    par: 'Minimo',
    yourStart: 'La tua partenza',
    stillNeeded: 'Mancano',
    guessPlaceholder: 'Nomina un paese',
    guessingAs: 'Giochi come',
    player: 'Giocatore',
    waiting: 'In attesa del tuo compagno',
    bothHere: 'Ci siete entrambi',
    reconnecting: 'Riconnessione…',
    connecting: 'Connessione…',
    invite: 'Invita',
    copied: 'Copiato',
    leave: 'Esci',
    back: 'Indietro',
    wholeWorld: 'Tutto il mondo',
    youMet: 'Vi siete incontrati',
    perfect: 'Perfetto — non si poteva fare con meno.',
    againstPar: 'Punti {score}, minimo {par}.',
    yourRoute: 'Il vostro percorso',
    shortestRoute: 'Il percorso più breve',
    newGame: 'Nuova partita',
    you: 'Tu',
    partner: 'Compagno',
    partnerNamed: 'Il compagno ha nominato',
    rejectUnknown: '«{text}» non è un paese di questo gioco.',
    rejectOutOfPlay: '{country} non ha confini terrestri con nessuno.',
    rejectWrongLandmass: '{country} si trova su un’altra massa continentale.',
    rejectAlreadyNamed: '{country} è già sul tabellone.',
    rejectGameOver: 'Vi siete già incontrati.',
    errBadRoom: 'Questo codice stanza non sembra corretto.',
    errRoomFull: 'Questa stanza ha già due giocatori.',
    errTakenOver: 'Hai aperto il gioco altrove.',
    errGeneric: 'Qualcosa è andato storto.',
    modeMeet: 'Incontrarsi a metà strada',
    modeMeetHint: 'Due partenze segrete. Nominate paesi finché i due lati non si uniscono.',
    modeContinent: 'Riempire un continente',
    modeContinentHint: 'Nessuna partenza. Nominate insieme tutti i paesi di un continente.',
    chooseContinent: 'Quale continente?',
    randomContinent: 'Sorprendici',
    named: 'Nominati',
    missed: 'Mancati',
    giveUp: 'Mostra quel che resta',
    filledIt: 'Lo avete completato',
    gaveUp: 'Ecco il resto',
    rejectWrongContinent: '{country} non è in questo continente.',
    showOutlines: 'Mostra i contorni',
    hideOutlines: 'Nascondi i contorni',
    modeIdentify: 'Indovina il paese',
    modeIdentifyHint: 'Un paese si illumina sulla mappa. Di quale si tratta?',
    whichCountry: 'Quale paese è evidenziato?',
    skip: 'Salta',
    correct: 'Giusti',
    continents: {
      europe: 'Europa',
      asia: 'Asia',
      africa: 'Africa',
      'north-america': 'America del Nord',
      'south-america': 'America del Sud',
      oceania: 'Oceania',
    },
  },

  nl: {
    title: 'Elkaar in het midden treffen',
    tagline:
      'Jullie beginnen allebei in een geheim land. Noem landen — welk dan ook, in willekeurige volgorde — tot jullie twee kanten aan elkaar vast zitten. Hoe minder, hoe beter.',
    language: 'Taal',
    twoPhones: 'Twee telefoons',
    twoPhonesHint: 'Eén van jullie start een spel en stuurt de ander de link.',
    startGame: 'Spel starten',
    codePlaceholder: 'Of voer een code in',
    join: 'Meedoen',
    codeError: 'Kamercodes zijn vier tekens.',
    oneDevice: 'Eén apparaat',
    oneDeviceHint: 'Geef hem door, of speel zelf beide kanten.',
    playHere: 'Hier spelen',
    score: 'Score',
    par: 'Minimum',
    yourStart: 'Jouw start',
    stillNeeded: 'Nog nodig',
    guessPlaceholder: 'Noem een land',
    guessingAs: 'Je speelt als',
    player: 'Speler',
    waiting: 'Wachten op je partner',
    bothHere: 'Allebei aanwezig',
    reconnecting: 'Opnieuw verbinden…',
    connecting: 'Verbinden…',
    invite: 'Uitnodigen',
    copied: 'Gekopieerd',
    leave: 'Verlaten',
    back: 'Terug',
    wholeWorld: 'Hele wereld',
    youMet: 'Jullie hebben elkaar gevonden',
    perfect: 'Perfect — minder kon niet.',
    againstPar: 'Score {score}, minimum {par}.',
    yourRoute: 'Jullie route',
    shortestRoute: 'Kortst mogelijke route',
    newGame: 'Nieuw spel',
    you: 'Jij',
    partner: 'Partner',
    partnerNamed: 'Partner noemde',
    rejectUnknown: '“{text}” is geen land in dit spel.',
    rejectOutOfPlay: '{country} heeft met niemand een landgrens.',
    rejectWrongLandmass: '{country} ligt op een andere landmassa.',
    rejectAlreadyNamed: '{country} staat al op het bord.',
    rejectGameOver: 'Jullie hebben elkaar al gevonden.',
    errBadRoom: 'Die kamercode klopt niet.',
    errRoomFull: 'Die kamer heeft al twee spelers.',
    errTakenOver: 'Je hebt het spel ergens anders geopend.',
    errGeneric: 'Er ging iets mis.',
    modeMeet: 'Elkaar in het midden treffen',
    modeMeetHint: 'Twee geheime startlanden. Noem landen tot jullie kanten aan elkaar vast zitten.',
    modeContinent: 'Een werelddeel vullen',
    modeContinentHint: 'Geen start. Noem samen elk land van één werelddeel.',
    chooseContinent: 'Welk werelddeel?',
    randomContinent: 'Verras ons',
    named: 'Genoemd',
    missed: 'Gemist',
    giveUp: 'Laat de rest zien',
    filledIt: 'Jullie hebben hem vol',
    gaveUp: 'Dit is de rest',
    rejectWrongContinent: '{country} ligt niet in dit werelddeel.',
    showOutlines: 'Grenzen tonen',
    hideOutlines: 'Grenzen verbergen',
    modeIdentify: 'Raad het land',
    modeIdentifyHint: 'Eén land licht op de kaart op. Zeg welk.',
    whichCountry: 'Welk land is gemarkeerd?',
    skip: 'Overslaan',
    correct: 'Goed',
    continents: {
      europe: 'Europa',
      asia: 'Azië',
      africa: 'Afrika',
      'north-america': 'Noord-Amerika',
      'south-america': 'Zuid-Amerika',
      oceania: 'Oceanië',
    },
  },

  pt: {
    title: 'Encontrar-se no meio',
    tagline:
      'Cada um começa num país secreto. Digam nomes de países — qualquer um, em qualquer ordem — até os dois lados se juntarem. Quantos menos, melhor.',
    language: 'Idioma',
    twoPhones: 'Dois telemóveis',
    twoPhonesHint: 'Um de vocês começa um jogo e envia o link ao outro.',
    startGame: 'Começar jogo',
    codePlaceholder: 'Ou introduza um código',
    join: 'Entrar',
    codeError: 'Os códigos têm quatro caracteres.',
    oneDevice: 'Um dispositivo',
    oneDeviceHint: 'Passem-no entre vocês, ou jogue os dois lados.',
    playHere: 'Jogar aqui',
    score: 'Pontos',
    par: 'Mínimo',
    yourStart: 'O teu início',
    stillNeeded: 'Faltam',
    guessPlaceholder: 'Diga um país',
    guessingAs: 'A jogar como',
    player: 'Jogador',
    waiting: 'À espera do teu parceiro',
    bothHere: 'Os dois aqui',
    reconnecting: 'A reconectar…',
    connecting: 'A conectar…',
    invite: 'Convidar',
    copied: 'Copiado',
    leave: 'Sair',
    back: 'Voltar',
    wholeWorld: 'Mundo inteiro',
    youMet: 'Encontraram-se',
    perfect: 'Perfeito — não dava com menos.',
    againstPar: 'Pontos {score}, mínimo {par}.',
    yourRoute: 'O vosso percurso',
    shortestRoute: 'O percurso mais curto',
    newGame: 'Novo jogo',
    you: 'Tu',
    partner: 'Parceiro',
    partnerNamed: 'O parceiro disse',
    rejectUnknown: '«{text}» não é um país deste jogo.',
    rejectOutOfPlay: '{country} não tem fronteira terrestre com ninguém.',
    rejectWrongLandmass: '{country} está noutra massa de terra.',
    rejectAlreadyNamed: '{country} já está no tabuleiro.',
    rejectGameOver: 'Já se encontraram.',
    errBadRoom: 'Esse código de sala não parece correto.',
    errRoomFull: 'Essa sala já tem dois jogadores.',
    errTakenOver: 'Abriu o jogo noutro sítio.',
    errGeneric: 'Algo correu mal.',
    modeMeet: 'Encontrar-se no meio',
    modeMeetHint: 'Dois inícios secretos. Digam países até os dois lados se juntarem.',
    modeContinent: 'Preencher um continente',
    modeContinentHint: 'Sem início. Digam juntos todos os países de um continente.',
    chooseContinent: 'Que continente?',
    randomContinent: 'Surpreendam-nos',
    named: 'Ditos',
    missed: 'Faltaram',
    giveUp: 'Mostrar o que falta',
    filledIt: 'Preencheram tudo',
    gaveUp: 'Aqui está o resto',
    rejectWrongContinent: '{country} não fica neste continente.',
    showOutlines: 'Mostrar contornos',
    hideOutlines: 'Ocultar contornos',
    modeIdentify: 'Adivinha o país',
    modeIdentifyHint: 'Um país acende no mapa. Digam qual é.',
    whichCountry: 'Que país está destacado?',
    skip: 'Saltar',
    correct: 'Certos',
    continents: {
      europe: 'Europa',
      asia: 'Ásia',
      africa: 'África',
      'north-america': 'América do Norte',
      'south-america': 'América do Sul',
      oceania: 'Oceânia',
    },
  },

  ru: {
    title: 'Встретиться посередине',
    tagline:
      'Каждый начинает в своей секретной стране. Называйте страны — любые, в любом порядке — пока две стороны не соединятся. Чем меньше, тем лучше.',
    language: 'Язык',
    twoPhones: 'Два телефона',
    twoPhonesHint: 'Один начинает игру и отправляет другому ссылку.',
    startGame: 'Начать игру',
    codePlaceholder: 'Или введите код',
    join: 'Войти',
    codeError: 'Код комнаты — четыре символа.',
    oneDevice: 'Одно устройство',
    oneDeviceHint: 'Передавайте его друг другу или играйте за обоих.',
    playHere: 'Играть здесь',
    score: 'Счёт',
    par: 'Минимум',
    yourStart: 'Ваш старт',
    stillNeeded: 'Осталось',
    guessPlaceholder: 'Назовите страну',
    guessingAs: 'Вы играете за',
    player: 'Игрок',
    waiting: 'Ждём вашего напарника',
    bothHere: 'Оба на месте',
    reconnecting: 'Переподключение…',
    connecting: 'Подключение…',
    invite: 'Пригласить',
    copied: 'Скопировано',
    leave: 'Выйти',
    back: 'Назад',
    wholeWorld: 'Весь мир',
    youMet: 'Вы встретились',
    perfect: 'Идеально — меньше было нельзя.',
    againstPar: 'Счёт {score}, минимум {par}.',
    yourRoute: 'Ваш маршрут',
    shortestRoute: 'Кратчайший маршрут',
    newGame: 'Новая игра',
    you: 'Вы',
    partner: 'Напарник',
    partnerNamed: 'Напарник назвал',
    rejectUnknown: '«{text}» — не страна в этой игре.',
    rejectOutOfPlay: 'У страны {country} нет сухопутной границы ни с кем.',
    rejectWrongLandmass: '{country} — на другом материке.',
    rejectAlreadyNamed: '{country} уже на доске.',
    rejectGameOver: 'Вы уже встретились.',
    errBadRoom: 'Код комнаты выглядит неверно.',
    errRoomFull: 'В этой комнате уже двое.',
    errTakenOver: 'Вы открыли игру в другом месте.',
    errGeneric: 'Что-то пошло не так.',
    modeMeet: 'Встретиться посередине',
    modeMeetHint: 'Два секретных старта. Называйте страны, пока стороны не соединятся.',
    modeContinent: 'Заполнить материк',
    modeContinentHint: 'Без старта. Назовите вместе все страны одного материка.',
    chooseContinent: 'Какой материк?',
    randomContinent: 'Удивите нас',
    named: 'Названо',
    missed: 'Пропущено',
    giveUp: 'Показать остальное',
    filledIt: 'Вы заполнили его',
    gaveUp: 'Вот остальное',
    rejectWrongContinent: '{country} не на этом материке.',
    showOutlines: 'Показать границы',
    hideOutlines: 'Скрыть границы',
    modeIdentify: 'Угадайте страну',
    modeIdentifyHint: 'На карте загорается одна страна. Назовите её.',
    whichCountry: 'Какая страна выделена?',
    skip: 'Пропустить',
    correct: 'Верно',
    continents: {
      europe: 'Европа',
      asia: 'Азия',
      africa: 'Африка',
      'north-america': 'Северная Америка',
      'south-america': 'Южная Америка',
      oceania: 'Океания',
    },
  },
}

/** Fills `{name}` placeholders. The only formatting the interface needs. */
export function format(template: string, values: Record<string, string | number>): string {
  return template.replace(/\{(\w+)\}/g, (whole, key: string) =>
    key in values ? String(values[key]) : whole,
  )
}
